name: publish

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-run-wait@v1

      - name: Find cache of node_modules
        id: node_modules_cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules_${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Execute only when no cache are found
      - name: Install dependencies
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: |
          yarn --production=false --frozen-lockfile

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
